name: Continous Integration

on:
  push:
    branches: [main,feature/branch]
  
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: az login check
        run: |
          az account show 
          az group list  
      
      - name: Run a single line script
        run: echo Hello,world!

      - name: custom script
        run: |
          ls -al

      - name: check java version
        run: java -version

      - name: npm ko install karna
        run: npm install

      - name: npm build karna
        run: CI=false npm run build  

      - name: docker check karna hai
        run: |
          docker -v
          docker  
          docker images -a
      - name: docker build karna
        run: |
          docker build -t elearn-frontend:v5 .   
          docker images -a
         
      - name: DockerHub login
        run: echo "${{ secrets.dockerhubpassword }}" | docker login -u "${{ secrets.dockerhubusername }}" --password-stdin
      
      - name: docker image check karna
        run : docker images

      - name: dockerhub par pushkarna
        run: |
          docker tag elearn-frontend:v5 amitirisha/elearn-frontend
          docker push amitirisha/elearn-frontend  

      
      
  
